<a href="https://colab.research.google.com/github/thecodingAdi/ai-ml-playground/blob/main/Basic_Layer_making_in_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras import layers
import pandas as pd

In [4]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [5]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [6]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [7]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

Normalisation

In [8]:
X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min + 1e-8)

In [9]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.25, random_state=42, stratify=y
)

In [13]:
model = keras.Sequential([
    layers.Input(shape= (X_train.shape[1],)),
    layers.Dense(8,activation= 'relu'),
    layers.Dense(1,activation = 'sigmoid')
])

In [15]:
model.compile(optimizer='sgd',loss = 'binary_crossentropy',metrics= ['accuracy'])

In [19]:
# Cast DataFrames and Series to float32 NumPy arrays
X_train_arr = X_train.to_numpy().astype('float32')
y_train_arr = y_train.to_numpy().astype('float32')
X_test_arr = X_test.to_numpy().astype('float32')
y_test_arr = y_test.to_numpy().astype('float32')

# Train the model
history = model.fit(
    X_train_arr,
    y_train_arr,
    validation_data=(X_test_arr, y_test_arr),
    epochs=100,
    batch_size=4,
    verbose=1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 1.0000 - loss: 0.3370 - val_accuracy: 1.0000 - val_loss: 0.3405
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.3379 - val_accuracy: 1.0000 - val_loss: 0.3398
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.3378 - val_accuracy: 1.0000 - val_loss: 0.3392
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.3379 - val_accuracy: 1.0000 - val_loss: 0.3385
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.3352 - val_accuracy: 1.0000 - val_loss: 0.3379
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.3348 - val_accuracy: 1.0000 - val_loss: 0.3373
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.3366 - val_accuracy: 1.0000 - val_loss: 0.3368
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.3341 - val_accuracy: 1.0000 - val_loss: 0.3362
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.3362 - val_accuracy: 1.0000 - val_loss: 0.3356
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.3343 - val_accuracy: 1.0000 - val_loss: 0.3350
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.3331 - val_accuracy: 1.0000 - val_loss: 0.3344
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.3322 - val_accuracy: 1.0000 - val_loss: 0.3338
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.3331 - val_accuracy: 1.0000 - val_loss: 0.3332
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.3316 - val_accuracy: 1.0000 - val_loss: 0.3326
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.3313 - val_accuracy: 1.0000 - val_loss: 0.3320
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.3322 - val_accuracy: 1.0000 - val_loss: 0.3315
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.3305 - val_accuracy: 1.0000 - val_loss: 0.3310
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.3305 - val_accuracy: 1.0000 - val_loss: 0.3305
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.3332 - val_accuracy: 1.0000 - val_loss: 0.3300
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.3308 - val_accuracy: 1.0000 - val_loss: 0.3295
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.3287 - val_accuracy: 1.0000 - val_loss: 0.3290
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.3297 - val_accuracy: 1.0000 - val_loss: 0.3285
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.3278 - val_accuracy: 1.0000 - val_loss: 0.3279
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.3285 - val_accuracy: 1.0000 - val_loss: 0.3274
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.3276 - val_accuracy: 1.0000 - val_loss: 0.3268
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.3287 - val_accuracy: 1.0000 - val_loss: 0.3262
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.3274 - val_accuracy: 1.0000 - val_loss: 0.3257
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.3263 - val_accuracy: 1.0000 - val_loss: 0.3253
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.3253 - val_accuracy: 1.0000 - val_loss: 0.3248
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.3254 - val_accuracy: 1.0000 - val_loss: 0.3243
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.3246 - val_accuracy: 1.0000 - val_loss: 0.3237
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.3252 - val_accuracy: 1.0000 - val_loss: 0.3232
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.3249 - val_accuracy: 1.0000 - val_loss: 0.3227
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.3239 - val_accuracy: 1.0000 - val_loss: 0.3222
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.3232 - val_accuracy: 1.0000 - val_loss: 0.3218
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.3223 - val_accuracy: 1.0000 - val_loss: 0.3213
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.3221 - val_accuracy: 1.0000 - val_loss: 0.3208
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.3219 - val_accuracy: 1.0000 - val_loss: 0.3203
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.3241 - val_accuracy: 1.0000 - val_loss: 0.3197
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.3219 - val_accuracy: 1.0000 - val_loss: 0.3193
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.3249 - val_accuracy: 1.0000 - val_loss: 0.3188
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.3209 - val_accuracy: 1.0000 - val_loss: 0.3184
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 1.0000 - loss: 0.3214 - val_accuracy: 1.0000 - val_loss: 0.3179
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.3208 - val_accuracy: 1.0000 - val_loss: 0.3173
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.3207 - val_accuracy: 1.0000 - val_loss: 0.3168
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.3192 - val_accuracy: 1.0000 - val_loss: 0.3164
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.3180 - val_accuracy: 1.0000 - val_loss: 0.3159
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.3191 - val_accuracy: 1.0000 - val_loss: 0.3155
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.3178 - val_accuracy: 1.0000 - val_loss: 0.3149
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 1.0000 - loss: 0.3176 - val_accuracy: 1.0000 - val_loss: 0.3145
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.3174 - val_accuracy: 1.0000 - val_loss: 0.3140
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.3173 - val_accuracy: 1.0000 - val_loss: 0.3135
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.3165 - val_accuracy: 1.0000 - val_loss: 0.3131
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.3153 - val_accuracy: 1.0000 - val_loss: 0.3126
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 1.0000 - loss: 0.3166 - val_accuracy: 1.0000 - val_loss: 0.3122
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 0.3149 - val_accuracy: 1.0000 - val_loss: 0.3116
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 1.0000 - loss: 0.3180 - val_accuracy: 1.0000 - val_loss: 0.3113
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 1.0000 - loss: 0.3143 - val_accuracy: 1.0000 - val_loss: 0.3108
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 1.0000 - loss: 0.3155 - val_accuracy: 1.0000 - val_loss: 0.3103
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 1.0000 - loss: 0.3133 - val_accuracy: 1.0000 - val_loss: 0.3099
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.3147 - val_accuracy: 1.0000 - val_loss: 0.3094
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.3129 - val_accuracy: 1.0000 - val_loss: 0.3090
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.3121 - val_accuracy: 1.0000 - val_loss: 0.3086
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 1.0000 - loss: 0.3120 - val_accuracy: 1.0000 - val_loss: 0.3081
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 1.0000 - loss: 0.3112 - val_accuracy: 1.0000 - val_loss: 0.3076
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 1.0000 - loss: 0.3110 - val_accuracy: 1.0000 - val_loss: 0.3072
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 1.0000 - loss: 0.3137 - val_accuracy: 1.0000 - val_loss: 0.3067
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 1.0000 - loss: 0.3104 - val_accuracy: 1.0000 - val_loss: 0.3062
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.3098 - val_accuracy: 1.0000 - val_loss: 0.3058
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.3098 - val_accuracy: 1.0000 - val_loss: 0.3053
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.3093 - val_accuracy: 1.0000 - val_loss: 0.3049
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.3099 - val_accuracy: 1.0000 - val_loss: 0.3045
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.3082 - val_accuracy: 1.0000 - val_loss: 0.3040
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.3091 - val_accuracy: 1.0000 - val_loss: 0.3036
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.3078 - val_accuracy: 1.0000 - val_loss: 0.3032
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.3083 - val_accuracy: 1.0000 - val_loss: 0.3028
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.3096 - val_accuracy: 1.0000 - val_loss: 0.3023
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.3069 - val_accuracy: 1.0000 - val_loss: 0.3019
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.3063 - val_accuracy: 1.0000 - val_loss: 0.3015
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.3062 - val_accuracy: 1.0000 - val_loss: 0.3010
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.3068 - val_accuracy: 1.0000 - val_loss: 0.3005
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.3053 - val_accuracy: 1.0000 - val_loss: 0.3002
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.3046 - val_accuracy: 1.0000 - val_loss: 0.2997
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.3055 - val_accuracy: 1.0000 - val_loss: 0.2993
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.3049 - val_accuracy: 1.0000 - val_loss: 0.2988
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.3043 - val_accuracy: 1.0000 - val_loss: 0.2983
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.3031 - val_accuracy: 1.0000 - val_loss: 0.2979
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.3030 - val_accuracy: 1.0000 - val_loss: 0.2975
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.3029 - val_accuracy: 1.0000 - val_loss: 0.2970
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.3035 - val_accuracy: 1.0000 - val_loss: 0.2966
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.3025 - val_accuracy: 1.0000 - val_loss: 0.2962
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.3032 - val_accuracy: 1.0000 - val_loss: 0.2958
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.3011 - val_accuracy: 1.0000 - val_loss: 0.2954
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.3012 - val_accuracy: 1.0000 - val_loss: 0.2950
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.3023 - val_accuracy: 1.0000 - val_loss: 0.2947
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.3004 - val_accuracy: 1.0000 - val_loss: 0.2943
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2999 - val_accuracy: 1.0000 - val_loss: 0.2938
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.2993 - val_accuracy: 1.0000 - val_loss: 0.2934
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.2996 - val_accuracy: 1.0000 - val_loss: 0.2930
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2991 - val_accuracy: 1.0000 - val_loss: 0.2926

In [20]:
from tensorflow.keras import optimizers

In [21]:
opt = optimizers.SGD(learning_rate = 0.01, momentum = 0.9)