<a href="https://colab.research.google.com/github/thecodingAdi/ai-ml-playground/blob/main/GridSearch_CV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<!-- Cleaned: GitHub Credentials section -->

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X = df.drop('species', axis=1)
y = df['species']

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

<!-- Cleaned: Clone Repository section -->

In [7]:
from sklearn.neighbors import KNeighborsClassifier

In [8]:
model_knn = KNeighborsClassifier(n_neighbors=5)

<!-- Cleaned: Add Changes and Push section -->

In [9]:
model_knn.fit(X_train, y_train)

KNeighborsClassifier()

<!-- Cleaned: Save and Push specific files section -->

In [10]:
model_knn.score(X_test, y_test)

0.98

In [11]:
from sklearn.svm import SVC

In [12]:
model_svm = SVC(C=30, gamma='auto', kernel= 'rbf')

<!-- Cleaned: Create and Push a New Working File section -->

In [13]:
model_svm.fit(X_train, y_train)

SVC(C=30, gamma='auto')

<!-- Cleaned: Push to GitHub instructions -->

In [14]:
model_svm.score(X_test, y_test)

0.98

In [15]:
 # Using Grid Search CV

In [16]:
from sklearn.model_selection import GridSearchCV

In [17]:
classifier = GridSearchCV((model_svm),{
    'C' : [1,10,20,30],
    'kernel' : ['rbf', 'linear']
}, cv=5, return_train_score=False)

In [18]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(C=30, gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [19]:
classifier.cv_results_

{'mean_fit_time': array([0.00657234, 0.00372005, 0.00339127, 0.00322709, 0.00538592,
        0.00721998, 0.00358882, 0.00402064]),
 'std_fit_time': array([0.00255638, 0.00036086, 0.00017674, 0.00017758, 0.00199056,
        0.00354256, 0.00046982, 0.00071163]),
 'mean_score_time': array([0.00510693, 0.00271654, 0.0030261 , 0.00305057, 0.00317492,
        0.00439825, 0.00267677, 0.00274172]),
 'std_score_time': array([2.25708195e-03, 7.60345221e-05, 8.76688822e-04, 1.34106903e-03,
        8.30118804e-04, 2.39980922e-03, 4.28154031e-04, 3.19299134e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [20]:
result = pd.DataFrame(classifier.cv_results_)

In [21]:
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006572,0.002556,0.005107,0.002257,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.003720,0.000361,0.002717,0.000076,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.003391,0.000177,0.003026,0.000877,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.003227,0.000178,0.003051,0.001341,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.005386,0.001991,0.003175,0.000830,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.007220,0.003543,0.004398,0.002400,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.003589,0.000470,0.002677,0.000428,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.004021,0.000712,0.002742,0.000319,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [22]:
result[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [23]:
classifier2 = GridSearchCV((model_knn),{
    'n_neighbors' : [1,5,10],
    'algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'metric' : ['minkowski', 'euclidean', 'manhattan'],
    'weights' : ['uniform', 'distance']
}, cv=5, return_train_score=False)

In [24]:
classifier2.fit(X,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'metric': ['minkowski', 'euclidean', 'manhattan'],
                         'n_neighbors': [1, 5, 10],
                         'weights': ['uniform', 'distance']})

In [25]:
result2 = pd.DataFrame(classifier2.cv_results_)
result2

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_metric,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003223,0.000286,0.005178,0.000971,auto,minkowski,1,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,49
1,0.006471,0.005237,0.005142,0.002844,auto,minkowski,1,distance,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,49
2,0.003600,0.000809,0.005558,0.001981,auto,minkowski,5,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,17
3,0.003106,0.000155,0.003392,0.000227,auto,minkowski,5,distance,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,32
4,0.005441,0.002537,0.008282,0.003611,auto,minkowski,10,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.966667,1.000000,1.000000,0.933333,1.0,0.980000,0.026667,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,0.002681,0.000065,0.003190,0.000440,brute,manhattan,1,distance,"{'algorithm': 'brute', 'metric': 'manhattan', ...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,49
68,0.002665,0.000073,0.004345,0.000809,brute,manhattan,5,uniform,"{'algorithm': 'brute', 'metric': 'manhattan', ...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,41
69,0.003230,0.000872,0.003947,0.001422,brute,manhattan,5,distance,"{'algorithm': 'brute', 'metric': 'manhattan', ...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,41
70,0.003894,0.001926,0.004019,0.000199,brute,manhattan,10,uniform,"{'algorithm': 'brute', 'metric': 'manhattan', ...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,17
71,0.002743,0.000126,0.003109,0.000101,brute,manhattan,10,distance,"{'algorithm': 'brute', 'metric': 'manhattan', ...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,32

In [26]:
result2[['param_n_neighbors','param_algorithm','param_metric','param_weights','mean_test_score']]

,param_n_neighbors,param_algorithm,param_metric,param_weights,mean_test_score
0,1,auto,minkowski,uniform,0.960000
1,1,auto,minkowski,distance,0.960000
2,5,auto,minkowski,uniform,0.973333
3,5,auto,minkowski,distance,0.966667
4,10,auto,minkowski,uniform,0.980000
...,...,...,...,...,...
67,1,brute,manhattan,distance,0.960000
68,5,brute,manhattan,uniform,0.960000
69,5,brute,manhattan,distance,0.960000
70,10,brute,manhattan,uniform,0.973333
71,10,brute,manhattan,distance,0.966667

## Using Random Search CV

In [27]:
from sklearn.model_selection import RandomizedSearchCV

In [34]:
classifier_r = RandomizedSearchCV((model_svm),{
    'C' : [1,10,20,30],
    'kernel' : ['rbf', 'linear']
}, cv=5, return_train_score=False, n_iter=4)

In [35]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(C=30, gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [36]:
result_r = pd.DataFrame(classifier_r.cv_results_)
result_r

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002524,0.000518,0.001816,0.000433,linear,20,"{'kernel': 'linear', 'C': 20}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,4
1,0.002064,0.000028,0.001573,0.000029,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,3
2,0.001953,0.000035,0.001519,0.000013,linear,1,"{'kernel': 'linear', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.001962,0.000025,0.001532,0.000020,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,2

In [37]:
result_r[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       20       linear         0.966667
1       20          rbf         0.966667
2        1       linear         0.980000
3       10       linear         0.973333